# USB Interface Example
# This example shows how to configure knxd-docker with a direct USB KNX interface

services:
  knxd:
    image: michelmu/knxd-docker:latest
    container_name: knxd-usb
    restart: unless-stopped
    
    # Port mappings
    ports:
      - "6720:6720/tcp"   # KNX daemon port
      - "3671:3671/udp"   # KNXnet/IP port
    
    # Device mappings for USB interface
    devices:
      - "/dev/bus/usb:/dev/bus/usb:rwm"
      - "/dev/mem:/dev/mem:rw"
    
    # Required capabilities for hardware access
    cap_add:
      - SYS_MODULE
      - SYS_RAWIO
    
    # Environment variables for USB configuration
    environment:
      # Core configuration
      - ADDRESS=1.5.1                    # KNX physical address
      - CLIENT_ADDRESS=1.5.2:10          # Client address range (start:count)
      - INTERFACE=usb                    # USB interface type
      
      # USB-specific configuration (choose one method)
      - USB_DEVICE=/dev/bus/usb/001/002  # Specific USB device path
      # OR
      # - USB_BUS=001:002                # USB bus identifier
      
      # Optional configuration
      - DEBUG_ERROR_LEVEL=error          # Logging level
      - FILTERS=single                   # Packet filtering
      - SERVER_INTERFACE=                # Network interface (empty = default)
    
    # Health check configuration
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep -v grep | grep knxd && netstat -ln | grep 6720"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Volume for persistent logs (optional)
    volumes:
      - knxd-logs:/var/log/knxd

# Named volume for logs
volumes:
  knxd-logs:
    driver: local
